version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: manageassets-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: manageassets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - manageassets-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: manageassets-backend
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=manageassets
      - JWT_SECRET=your-super-secret-jwt-key
      - NODE_ENV=production
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - manageassets-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: manageassets-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - manageassets-network

volumes:
  postgres_data:

networks:
  manageassets-network:
    driver: bridge
