[package]
name = "manage_assets"
version = "0.1.0"
edition = "2023_10"

[dependencies]
starknet = ">=2.3.1"

[lib]
sierra = true
casm = true

[[target.starknet-contract]]
sierra = true
casm = true

[tool.cairo-test]
workspace = true
